feat: Adiciona implementação do Exercício 01
raphaelhla/exercicios-new-rizon pull request #1
Opened 2023-10-12 03:34 UTC by raphaelhla

2023-10-12 03:37 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Raphael Agra] Exercício 1](https://trello.com/c/Uh7AYsqT/146-raphael-agra-exerc%C3%ADcio-1)

2023-10-13 19:25 UTC, matheus-yudi-newrizon requested changes

2023-10-13 19:25 UTC, matheus-yudi-newrizon commented on exercicio-01/exercicio-01.ts
> +function contaVogais(palavra: string): number {
É uma boa prática sempre documentar o nosso código, facilita o entendimento e a manutenção.

Sugestão de doc oficial: modelo de documentação do TSDoc (https://tsdoc.org/)

2023-10-13 19:25 UTC, matheus-yudi-newrizon commented on exercicio-01/exercicio-01.ts
> +	const vogais: string[] = ["a", "e", "i", "o", "u", "A", "E", "I", "O", "U"];
Dicas:

- Poderia considerar as vogais acentuadas
- Para não precisar mapear todas as vogais e suas variantes (maiúscula/minúscula), você poderia transformar a palavra toda para lowercase ou uppercase.

2023-10-13 19:25 UTC, matheus-yudi-newrizon commented on exercicio-01/index.html
É uma boa prática sempre deixar o código "limpo", remover espaços em branco, identar os elementos e remover código comentado.

2023-10-13 19:25 UTC, matheus-yudi-newrizon commented on exercicio-01/exercicio-01.ts
> +function exibirResultado(): void {
Mesmo caso da anterior, documentar o método e adicionar comentários explicando o processo quando necessário.

2023-10-13 22:11 UTC, matheus-yudi-newrizon approved these changes

2023-10-13 22:12 UTC, merged