Feature/exercicio 02
raphaelhla/exercicios-new-rizon pull request #2
Opened 2023-10-12 08:28 UTC by raphaelhla

2023-10-12 08:29 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Raphael Agra] Exercício 2](https://trello.com/c/hTBVJjJD/147-raphael-agra-exerc%C3%ADcio-2)

2023-10-12 08:33 UTC, raphaelhla commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Raphael Agra] Exercício 2](https://trello.com/c/hTBVJjJD/147-raphael-agra-exerc%C3%ADcio-2)

2023-10-13 21:28 UTC, dairsposito requested changes

2023-10-13 21:28 UTC, dairsposito commented on exercicio-02/src/paradigma_funcional/paradigma_funcional.ts
> +function getBioById(id: number): string | undefined {
No paradigma funcional a função não deve acessar/modificar dados externos. Logo, como a lista a qual a função está manipulando está fora do escopo da função, é necessário informar a lista via parâmetro para a função.
Aplicar para demais funções no mesmo contexto.

2023-10-13 21:28 UTC, dairsposito commented on exercicio-02/src/paradigma_funcional/paradigma_funcional.ts
> +    return pessoa ? pessoa.bio : undefined;
Dica: aqui você pode escrever a mesma coisa da seguinte forma `return pessoa?.bio;`

2023-10-13 21:28 UTC, dairsposito commented on exercicio-02/src/paradigma_funcional/paradigma_funcional.ts
> +// Implementação deletePessoaById com o Paradigma Funcional
Neste caso, a nova lista deve ser retornada pela função, sem alterar/acessar a lista original.
Assim sendo, a lista também deve ser informada via parâmetros para a função.

2023-10-13 21:28 UTC, dairsposito commented on exercicio-02/src/paradigma_imperativo/paradigma_imperativo.ts
> +    let novaLista: Pessoa[] = [];
Nesse caso, não há necessidade de criar uma nova lista, basta alterar a lista original.

2023-10-13 23:56 UTC, dairsposito requested changes
Documentar as funções.

2023-10-13 23:56 UTC, dairsposito commented on exercicio-02/src/paradigma_funcional/paradigma_funcional.ts
Está bom, ficou faltando apenas documentar as funções.

2023-10-14 00:14 UTC, merged